// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Summon Software Labs.
//
// Completed-operation benchmark. Every measured operation is timed to its
// documented completion point:
//
//   append  validation, canonical encoding, segment write, durable flush,
//           read-back verification, staging manifest write and flush, manifest
//           slot publish, durable flush of the slot, read-back verification,
//           in-memory adoption and idempotency bookkeeping.
//   rollup  full resolution pass plus rollup assembly for the whole ledger.
//   reopen  close, open, deterministic replay of every committed record and
//           full integrity verification.
//   verify  read-only verification of the committed prefix from the path.
//
// Results are labelled REAL: they are measured on the host that ran them, with
// SYNTHETIC input generated by this program. No hardware measurement is
// claimed.

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>

#include "energy_ledger/energy_ledger.hpp"
#include "energy_ledger/test_support.hpp"

namespace {

using namespace energy_ledger;

std::string platform_label() {
#if defined(_WIN32) && defined(_M_X64)
  return "windows-x64";
#elif defined(_WIN32)
  return "windows";
#elif defined(__linux__)
  return "linux";
#else
  return "unknown";
#endif
}

std::string compiler_label() {
#if defined(_MSC_VER)
  return "msvc-" + std::to_string(_MSC_VER);
#elif defined(__clang__)
  return "clang-" + std::to_string(__clang_major__);
#elif defined(__GNUC__)
  return "gcc-" + std::to_string(__GNUC__);
#else
  return "unknown";
#endif
}

std::string build_label() {
#ifdef NDEBUG
  return "release";
#else
  return "debug";
#endif
}

EntryContent make_entry(std::uint64_t index) {
  EntryContent content;
  content.kind = (index % 7 == 0) ? EntryKind::Consumed : EntryKind::Delivered;
  content.quality = ObservationQuality::Verified;
  content.authority_tier = AuthorityTier::create(3).value();
  content.object = FacilityObjectRef::parse("facility/line-1").value();
  content.generation = GenerationRef::parse(index < 5000 ? "gen-1" : "gen-2").value();
  content.interval = IntervalRef::parse("interval-" + std::to_string(index)).value();
  content.clock_domain = ClockDomainRef::parse("utc").value();
  content.source_family = SourceFamilyRef::parse("revenue-meter").value();
  content.source_instance =
      SourceInstanceRef::parse("meter-" + std::to_string(index % 8)).value();
  content.authority = AuthorityRef::parse("metering-service").value();
  content.time_basis = TimeBasis::UtcUnixSeconds;
  const std::int64_t start = 1767225600 + static_cast<std::int64_t>(index) * 3600;
  content.interval_start = TimeTicks(start);
  content.interval_end = TimeTicks(start + 3600);
  content.observed_at = TimeTicks(start + 3600);
  content.source_revision = SourceRevision(1);
  content.source_generation = SourceGeneration(1);
  content.source_epoch = SourceEpoch(1);
  content.declared_value = 100 + static_cast<std::int64_t>(index % 900);
  content.declared_unit = EnergyUnit::KilowattHour;
  content.quantity = to_canonical_energy(content.declared_value, EnergyUnit::KilowattHour).value();
  return content;
}

double milliseconds_since(const std::chrono::steady_clock::time_point& start) {
  const auto elapsed = std::chrono::steady_clock::now() - start;
  return std::chrono::duration<double, std::milli>(elapsed).count();
}

}  // namespace

int main(int argc, char** argv) {
  std::uint64_t entries = 20000;
  std::uint64_t rollup_queries = 200;
  std::uint64_t reopen_repetitions = 3;
  bool keep = false;
  for (int index = 1; index < argc; ++index) {
    const std::string argument = argv[index];
    if (argument == "--entries" && index + 1 < argc) {
      entries = std::strtoull(argv[++index], nullptr, 10);
    } else if (argument == "--rollup-queries" && index + 1 < argc) {
      rollup_queries = std::strtoull(argv[++index], nullptr, 10);
    } else if (argument == "--reopen-repetitions" && index + 1 < argc) {
      reopen_repetitions = std::strtoull(argv[++index], nullptr, 10);
    } else if (argument == "--keep") {
      keep = true;
    } else if (argument == "--help") {
      std::cout << "usage: energy-ledger-bench [--entries N] [--rollup-queries N]"
                   " [--reopen-repetitions N] [--keep]\n";
      return 0;
    } else {
      std::cerr << "unknown argument '" << argument << "'\n";
      return 2;
    }
  }
  if (entries == 0 || rollup_queries == 0 || reopen_repetitions == 0) {
    std::cerr << "workload sizes must be positive\n";
    return 2;
  }

  const std::string store = "bench-store";
  auto removed = test_support::remove_directory_tree(store);
  if (!removed) {
    std::cerr << "could not clear the benchmark store: " << removed.error().detail << "\n";
    return 2;
  }

  std::cout << "Energy Ledger benchmark\n";
  std::cout << "label=REAL input=SYNTHETIC\n";
  std::cout << "library-version=" << kVersionString << " build=" << build_label()
            << " compiler=" << compiler_label() << " platform=" << platform_label() << "\n";
  std::cout << "workload entries=" << entries << " rollup-queries=" << rollup_queries
            << " reopen-repetitions=" << reopen_repetitions << "\n";

  CreateOptions create;
  create.fail_if_exists = false;
  auto ledger = Ledger::create(store, create);
  if (!ledger) {
    std::cerr << "create failed: " << ledger.error().describe() << "\n";
    return 2;
  }

  const auto append_start = std::chrono::steady_clock::now();
  for (std::uint64_t index = 0; index < entries; ++index) {
    AppendRequest request;
    request.content = make_entry(index);
    auto result = ledger.value().append(request);
    if (!result) {
      std::cerr << "append " << index << " failed: " << result.error().describe() << "\n";
      return 2;
    }
    if (result.value().sequence.value() != index + 1) {
      std::cerr << "append " << index << " produced an unexpected sequence\n";
      return 2;
    }
  }
  const double append_ms = milliseconds_since(append_start);

  auto audit = ledger.value().audit();
  if (!audit) {
    std::cerr << "audit failed: " << audit.error().describe() << "\n";
    return 2;
  }
  std::uint64_t committed_bytes = 0;
  for (const SegmentAudit& segment : audit.value().segments) {
    committed_bytes += segment.committed_bytes;
  }
  std::cout << "append completed-ops=" << entries << " total-ms=" << append_ms
            << " ops-per-second=" << (static_cast<double>(entries) * 1000.0 / append_ms)
            << " microseconds-per-op=" << (append_ms * 1000.0 / static_cast<double>(entries))
            << " committed-bytes=" << committed_bytes << "\n";

  RollupQuery query;
  query.object = FacilityObjectRef::parse("facility/line-1").value();
  query.options.max_contributors = 16;
  const auto rollup_start = std::chrono::steady_clock::now();
  std::uint64_t generated = 0;
  for (std::uint64_t index = 0; index < rollup_queries; ++index) {
    auto result = ledger.value().rollup(query);
    if (!result) {
      std::cerr << "rollup failed: " << result.error().describe() << "\n";
      return 2;
    }
    generated = result.value().entries_matched;
  }
  const double rollup_ms = milliseconds_since(rollup_start);
  std::cout << "rollup completed-ops=" << rollup_queries << " total-ms=" << rollup_ms
            << " ops-per-second=" << (static_cast<double>(rollup_queries) * 1000.0 / rollup_ms)
            << " microseconds-per-op=" << (rollup_ms * 1000.0 / static_cast<double>(rollup_queries))
            << " entries-resolved=" << generated << "\n";

  auto closed = ledger.value().close();
  if (!closed) {
    std::cerr << "close failed: " << closed.error().describe() << "\n";
    return 2;
  }

  std::vector<double> reopen_samples;
  for (std::uint64_t repetition = 0; repetition < reopen_repetitions; ++repetition) {
    const auto reopen_start = std::chrono::steady_clock::now();
    OpenOptions options;
    options.mode = AccessMode::ReadWrite;
    auto reopened = Ledger::open(store, options);
    if (!reopened) {
      std::cerr << "reopen failed: " << reopened.error().describe() << "\n";
      return 2;
    }
    auto verified = reopened.value().verify();
    if (!verified || !verified.value().ok) {
      std::cerr << "post-reopen verification failed\n";
      return 2;
    }
    if (verified.value().entries_checked != entries) {
      std::cerr << "post-reopen verification counted " << verified.value().entries_checked
                << " entries, expected " << entries << "\n";
      return 2;
    }
    const double sample = milliseconds_since(reopen_start);
    reopen_samples.push_back(sample);
    auto closed_again = reopened.value().close();
    if (!closed_again) {
      std::cerr << "close failed: " << closed_again.error().describe() << "\n";
      return 2;
    }
  }
  std::sort(reopen_samples.begin(), reopen_samples.end());
  const double median = reopen_samples[reopen_samples.size() / 2];
  std::cout << "reopen-with-replay-and-verify completed-ops=" << reopen_repetitions
            << " median-ms=" << median << " min-ms=" << reopen_samples.front()
            << " max-ms=" << reopen_samples.back() << " entries=" << entries << "\n";

  const auto verify_start = std::chrono::steady_clock::now();
  VerifyOptions verify_options;
  verify_options.deep = true;
  auto standalone = verify_store(store, verify_options);
  const double verify_ms = milliseconds_since(verify_start);
  if (!standalone) {
    std::cerr << "verify_store failed: " << standalone.error().describe() << "\n";
    return 2;
  }
  if (!standalone.value().ok) {
    std::cerr << "verify_store reported findings\n";
    return 2;
  }
  std::cout << "verify-read-only completed-ops=1 total-ms=" << verify_ms
            << " entries-checked=" << standalone.value().entries_checked
            << " bytes-checked=" << standalone.value().bytes_checked << "\n";

  if (!keep) {
    auto cleaned = test_support::remove_directory_tree(store);
    if (!cleaned) {
      std::cerr << "cleanup failed: " << cleaned.error().describe() << "\n";
      return 2;
    }
  }
  std::cout << "cleanup=" << (keep ? "retained" : "removed") << "\n";
  return 0;
}
